name: Build op-geth image Workflow

on:
  push:
  workflow_dispatch:
    inputs:
      op_geth_ref_name:
        type: string
        description: 'op_geth branch name to use for building the image'
        required: false
        default: 'main'

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    env:
      ROLLUP_CLIENT_REF_NAME: ${{ github.ref_name }}
      OP_GETH_REF_NAME: ${{ inputs.op_geth_ref_name || 'main' }}

    steps:
      - name: Checkout rome-rollup-clients
        uses: actions/checkout@v4
        with:
          repository: rome-labs/rome-rollup-clients
          path: rome-rollup-clients
          ref: ${{ env.ROLLUP_CLIENT_REF_NAME }}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: Checkout op-geth
        uses: actions/checkout@v4
        with:
          repository: rome-labs/op-geth
          path: op-geth
          ref: ${{ env.OP_GETH_REF_NAME }}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push amd64 image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: rome-rollup-clients/op-geth/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: romelabs/rollup-op-geth:${{ env.ROLLUP_CLIENT_REF_NAME }}

  build-arm64:
    runs-on: ubuntu-24.04-arm
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    env:
      ROLLUP_CLIENT_REF_NAME: ${{ github.ref_name }}
      OP_GETH_REF_NAME: ${{ inputs.op_geth_ref_name || 'main' }}

    steps:
      - name: Checkout rome-rollup-clients
        uses: actions/checkout@v4
        with:
          repository: rome-labs/rome-rollup-clients
          path: rome-rollup-clients
          ref: ${{ env.ROLLUP_CLIENT_REF_NAME }}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: Checkout op-geth
        uses: actions/checkout@v4
        with:
          repository: rome-labs/op-geth
          path: op-geth
          ref: ${{ env.OP_GETH_REF_NAME }}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push arm64 image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: rome-rollup-clients/op-geth/Dockerfile
          platforms: linux/arm64
          push: true
          provenance: false
          tags: romelabs/rollup-op-geth:${{ env.ROLLUP_CLIENT_REF_NAME }}

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    env:
      ROLLUP_CLIENT_REF_NAME: ${{ github.ref_name }}
      OP_GETH_REF_NAME: ${{ inputs.op_geth_ref_name || 'main' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create romelabs/rollup-op-geth:${{ env.ROLLUP_CLIENT_REF_NAME }} \
            --amend romelabs/rollup-op-geth@${{ needs.build-amd64.outputs.digest }} \
            --amend romelabs/rollup-op-geth@${{ needs.build-arm64.outputs.digest }}

          docker manifest push romelabs/rollup-op-geth:${{ env.ROLLUP_CLIENT_REF_NAME }}

      - name: Tag and push :latest if main
        if: ${{ env.ROLLUP_CLIENT_REF_NAME == 'main' && env.OP_GETH_REF_NAME == 'main' }}
        run: |
          docker manifest create romelabs/rollup-op-geth:latest \
            --amend romelabs/rollup-op-geth@${{ needs.build-amd64.outputs.digest }} \
            --amend romelabs/rollup-op-geth@${{ needs.build-arm64.outputs.digest }}

          docker manifest push romelabs/rollup-op-geth:latest
