name: Build op-geth image Workflow

on:
  push:

jobs:
  prepare_env:
    runs-on: ubuntu-latest
    env:
      # Set the Branch/Ref of the github repository to be used to tag op-geth docker image
      ROME_ROLLUP_CLIENT_REF_NAME: ${{github.ref_name}} # If updating this, also update the uses in the job call-reusable-tests at bottom of this file
      OP_GETH_REF_NAME: "main"

    outputs:
      rollup_client_ref_name: ${{ steps.set_rollup_client_ref.outputs.rollup_client_ref_name }}
      op_geth_ref_name: ${{ steps.set_rollup_client_ref.outputs.op_geth_ref_name }}

    steps:
      - name: 'Set REF NAME'
        id: set_rollup_client_ref
        run: |
          echo "rollup_client_ref_name=${{ env.ROME_ROLLUP_CLIENT_REF_NAME || 'main' }}" >> $GITHUB_OUTPUT
          echo "op_geth_ref_name=${{ env.OP_GETH_REF_NAME || 'main' }}" >> $GITHUB_OUTPUT

  call-reusable-build:
    uses: ./.github/workflows/reusable_wf_build.yml
    needs: prepare_env
    secrets: inherit
    with:
      op_geth_ref_name: ${{ needs.prepare_env.outputs.op_geth_ref_name }}
        
  update-latest-tag:
    runs-on: ubuntu-latest
    needs: [prepare_env, call-reusable-build]
    if: ${{needs.prepare_env.outputs.rollup_client_ref_name == 'main' && needs.prepare_env.outputs.op_geth_ref_name == 'main'}}
    steps:
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Set latest tag'
        run: |
          docker pull romelabs/rollup-op-geth:${{ needs.prepare_env.outputs.op_geth_ref_name }}
          docker tag romelabs/rollup-op-geth:${{ needs.prepare_env.outputs.op_geth_ref_name }} romelabs/rollup-op-geth:latest
          docker push romelabs/rollup-op-geth:latest
    