name: build_images

on:
  push:
  workflow_dispatch:

env:
  REF_NAME: ${{github.ref_name}}

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout rome-rollup-clients repository'
        uses: actions/checkout@main
        with:
          repository: rome-protocol/rome-rollup-clients
          path: rome-rollup-clients
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}
          
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build rome-rollup-clients image'
        uses: docker/build-push-action@v4.0.0
        with:
          context: rome-rollup-clients/
          push: true
          file: rome-rollup-clients/op-geth/Dockerfile
          tags: romeprotocol/rollup-op-geth:${{github.ref_name}}
          labels: romeprotocol/rollup-op-geth:${{github.ref_name}}
          
      - name: 'Set latest tag'
        if: |
          ( github.ref_name == 'main' )
        run: |
          docker pull romeprotocol/rollup-op-geth:${{github.ref_name}}
          docker tag romeprotocol/rollup-op-geth:${{github.ref_name}} romeprotocol/rollup-op-geth:latest
          docker push romeprotocol/rollup-op-geth:latest

