name: build_docker_image

on:
  workflow_call:
    inputs:
      op_geth_ref_name:
        type: string
        description: 'op_geth branch name to use for building the image'
        required: false
        default: 'main'

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Prepare environment variables from input'
        id: prepare_env
        run: |
          op_geth_ref_name='${{ inputs.op_geth_ref_name || 'main' }}'
          echo "OP_GETH_REF_NAME=$op_geth_ref_name" >> $GITHUB_ENV

      - name: 'Checkout rome-rollup-clients repository'
        uses: actions/checkout@main
        with:
          repository: rome-labs/rome-rollup-clients
          path: rome-rollup-clients
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}
  
      - name: 'Checkout op-geth reposotory'
        uses: actions/checkout@master
        with:
          path: op-geth
          repository: rome-labs/op-geth
          ref: ${{env.OP_GETH_REF_NAME}}
          token: ${{secrets.GIT_ROLLUP_TOKEN}}
      
      - name: 'list folders'
        run: |
          pwd
          ls -l
          ls -l op-geth
          ls -l rome-rollup-clients
          ls -l rome-rollup-clients/op-geth
      
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build op-geth image'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          file: rome-rollup-clients/op-geth/Dockerfile
          tags: romelabs/rollup-op-geth:${{env.OP_GETH_REF_NAME}}
          labels: romelabs/rollup-op-geth:${{env.OP_GETH_REF_NAME}}

      - name: 'Set latest tag'
        if: ${{env.OP_GETH_REF_NAME == 'main'}}
        run: |
          docker pull romelabs/rollup-op-geth:${{env.OP_GETH_REF_NAME}}
          docker tag romelabs/rollup-op-geth:${{env.OP_GETH_REF_NAME}} romelabs/rollup-op-geth:latest
          docker push romelabs/rollup-op-geth:latest
    